### ISSUE TITLE
OCSP Check results in internalerror

### ISSUE THREAD

**Issue by mrimann** [matteocorti/check_ssl_cert#191] opened 2020-03-25 08:29 UTC
**Describe the bug**\
We've implemented this module for checking the certificates of hosted websites of our customers. So far, everything worked out - but suddenly, without any known changes to the Icinga2 config, the check-script or the monitored webserver(s), the checks began to show an error:

> SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)

**To Reproduce**\
When trying to reproduce the behaviour on the CLI, I get the same result:

```
root@monitor05:~# /usr/lib/nagios/plugins/check_ssl_cert_from_git/check_ssl_cert -H www.autoag.ch --ocsp --ignore-exp --cn www.autoag.ch --altnames
SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
```
and with `-v` we get a few more lines of output:

```
root@monitor05:~# /usr/lib/nagios/plugins/check_ssl_cert_from_git/check_ssl_cert -H www.autoag.ch --ocsp --ignore-exp --cn www.autoag.ch --altnames -v
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
parsing the x509 certificate file
The certificate will expire in 368 day(s)
OCSP Error: Responder Error: internalerror (2)
SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
```

In this case the error was persistent now for >2h. The server we test against is an Apache Webserver - and even restarting the Apache didn't help or change the situation.

We've seen other domains show the exact same behaviour. These other domains were hosted on a mix of Nginx and Apache Webservers. On all those other domains, the problem has vanished without any intervention after some time.

This leaves me puzzled as I'm not sure if it's really an issue with this check script, or some other component.

**Expected behavior**\
For the above mentioned domain, the check should result in OK - at least when I trust the other external tools like the SSLLabs and Hardenize-Checks - they all result without any errors.

**System**\
 - OS: Ubuntu 18.04.4 LTS
 - check_ssl_cert Version: 1.111.0
- openssl Version: 1.1.1-1ubuntu2.1~18.04.5

**Comment by matteocorti** [comment] 2020-03-25 08:37
Hi thanks for the report.

I cannot reproduce the error on my machine. Could you please execute the the plugin with the -d option and post the output?

Cheers

Matteo

**Comment by mrimann** [comment] 2020-03-25 10:33
Hi Matteo

Here's the debug-output:

```
root@monitor05:~# /usr/lib/nagios/plugins/check_ssl_cert_from_git/check_ssl_cert -H www.autoag.ch --ocsp --ignore-exp --cn www.autoag.ch --altnames -v -d
[DBG] ROOT_CA =
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
[DBG] nmap binary not needed. No disallowed protocols
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.111.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
[DBG] OpenSSL configuration directory: /usr/lib/ssl
[DBG] 0 root certificates installed by default
[DBG] System info: Linux monitor05 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername www.autoag.ch
[DBG] '/usr/bin/openssl s_client' supports '-name': using monitor05
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost www.autoag.ch
[DBG] temporary file /tmp/check_ssl_certfgIcrY created
[DBG] temporary file /tmp/check_ssl_cert2nDCh7 created
[DBG] temporary file /tmp/check_ssl_certWVvim9 created
[DBG] temporary file /tmp/check_ssl_certQNZ61S created
downloading certificate to /tmp
[DBG] www.autoag.ch is not an IP address
[DBG] executing with timeout (15s): printf 'HEAD / HTTP/1.1\nHost: www.autoag.ch\nUser-Agent: check_ssl_cert/1.111.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect www.autoag.ch:443 -servername www.autoag.ch -showcerts -verify 6       2> /tmp/check_ssl_cert2nDCh7 1> /tmp/check_ssl_certfgIcrY
[DBG]   /usr/bin/timeout 15 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: www.autoag.ch\nUser-Agent: check_ssl_cert/1.111.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect www.autoag.ch:443 -servername www.autoag.ch -showcerts -verify 6       2> /tmp/check_ssl_cert2nDCh7 1> /tmp/check_ssl_certfgIcrY"
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/www.autoag.ch-443.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/www.autoag.ch-443.error
parsing the x509 certificate file
[DBG] ISSUERS =
[DBG]           Sectigo RSA Domain Validation Secure Server CA
[DBG]           USERTrust RSA Certification Authority
[DBG]           AddTrust External CA Root
[DBG]           AddTrust External CA Root
[DBG] subject=CN = autoag.ch
[DBG] CN         = autoag.ch
[DBG] CA         = Sectigo RSA Domain Validation Secure Server CA
[DBG] CA         = USERTrust RSA Certification Authority
[DBG] CA         = AddTrust External CA Root
[DBG] CA         = AddTrust External CA Root
[DBG] SERIAL     = EA0C137E8EA353B7CAE2E77BDF18CD89
[DBG] FINGERPRINT= 11:0F:D7:5E:57:53:4F:62:D9:14:38:51:63:39:50:E2:17:9B:3B:F0
[DBG] OCSP_URI   = http://ocsp.sectigo.com
[DBG] ISSUER_URI = http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt
[DBG]         Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Mar 28 23:59:59 2021 GMT'
[DBG] Hours until Mar 28 23:59:59 2021 GMT: 8845
The certificate will expire in 368 day(s)
[DBG] subjectAlternativeName = autoag.ch www.autoag.ch
[DBG] check CN: autoag.ch
[DBG] COMMON_NAME = www.autoag.ch
[DBG] ===============================
[DBG] checking altnames against www.autoag.ch
[DBG] check Altname: autoag.ch
[DBG] check Altname: www.autoag.ch
[DBG] CN check finished
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt to /tmp/check_ssl_certWVvim9
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt > /tmp/check_ssl_certWVvim9
[DBG]   /usr/bin/timeout 15 /bin/sh -c "/usr/bin/curl --silent --location http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt > /tmp/check_ssl_certWVvim9"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to /tmp/SectigoRSADomainValidationSecureServerCA.crt
[DBG] OCSP: host = ocsp.sectigo.com
[DBG] /usr/bin/openssl ocsp supports the -header option
[DBG] /usr/bin/openssl ocsp -header requires 'key=value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certWVvim9 -cert /tmp/check_ssl_certfgIcrY  -url http://ocsp.sectigo.com  -header HOST=ocsp.sectigo.com
[DBG] OCSP: response = Responder Error: internalerror (2)
[DBG] OCSP: not good. HTTP_PROXY =
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer "/tmp/check_ssl_certWVvim9" -cert "/tmp/check_ssl_certfgIcrY" -url "http://ocsp.sectigo.com" "" 2>&1
OCSP Error: Responder Error: internalerror (2)
[DBG] CRITICAL >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[DBG] prepend_critical_message: new message    = OCSP error (-v for details)
[DBG] prepend_critical_message: HOST           = www.autoag.ch
[DBG] prepend_critical_message: CN             = autoag.ch
[DBG] prepend_critical_message: SNI            =
[DBG] prepend_critical_message: FILE           =
[DBG] prepend_critical_message: SHORTNAME      = SSL_CERT
[DBG] prepend_critical_message: MSG            =
[DBG] prepend_critical_message: CRITICAL_MSG   =
[DBG] prepend_critical_message: ALL_MSG 1      =
[DBG] prepend_critical_message: MSG 2          = SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
[DBG] prepend_critical_message: CRITICAL_MSG 2 = SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
[DBG] prepend_critical_message: ALL_MSG 2      =
    SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
[DBG] CRITICAL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[DBG] cleaning up temporary files
[DBG]   /tmp/check_ssl_certfgIcrY
[DBG]   /tmp/check_ssl_cert2nDCh7
[DBG]   /tmp/check_ssl_certWVvim9
[DBG]   /tmp/check_ssl_certQNZ61S
[DBG] exiting with CRITICAL
[DBG] ALL_MSG =
    SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
[DBG] number of errors = 1
SSL_CERT CRITICAL autoag.ch: OCSP error (-v for details)|days=368;;;;
root@monitor05:~#
```

I've additionally ran that domain/website through other tests, e.g. https://www.digicert.com/help/ and the Check at DigiCert was at least temporarily showing the certificate to be revoked, see screenshot:

![image](https://user-images.githubusercontent.com/1093784/77527188-01a09780-6e8c-11ea-8beb-06dd94518f07.png)

Strange thing, now running the same test again is says "all good".

One other thought: I've noticed the Sectigo certificates to be signed by multiple paths of intermediates - could it be that this leads to some "flapping" or temporarily strange interpretation of the chain, depending on which tool evaluates it? (well, just wild guessing tbh)

Thanks for having a look in to it!
Cheers, Mario

**Comment by mrimann** [comment] 2020-03-25 12:30
Out of nothing, the error vanished away and the check now results in a "all fine" again:

```
root@monitor05:~# /usr/lib/nagios/plugins/check_ssl_cert_from_git/check_ssl_cert -H www.autoag.ch --ocsp --ignore-exp --cn www.autoag.ch --altnames -v
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
found GNU date with timestamp support: enabling date computations
downloading certificate to /tmp
parsing the x509 certificate file
The certificate will expire in 368 day(s)
SSL_CERT OK - x509 certificate 'autoag.ch' (www.autoag.ch) from 'Sectigo RSA Domain Validation Secure Server CA' valid until Mar 28 23:59:59 2021 GMT (expires in 368 days)|days=368;;;;
```

**Comment by matteocorti** [comment] 2020-03-25 16:08
Thanks I also don't get any error at the moment. I still want to check the command

```
/usr/bin/openssl ocsp -no_nonce -issuer "/tmp/check_ssl_certWVvim9" -cert "/tmp/check_ssl_certfgIcrY" -url "http://ocsp.sectigo.com" ""
```

The last empty parameter is very strange

**Comment by matteocorti** [comment] 2020-04-07 13:39
The strage ```""'''' are for ```$OCSP_HEADER'' which is **never** set

**Comment by mrimann** [comment] 2020-04-08 07:42
We've now repeatedly seen this issue pop-up and go-away by itself during the last days, across several domains (with mostly Comodo certificates), that are run on different servers (mostly Nginx, but also some Apaches). I could not detect any pattern out of it, so far it looks to occur "randomly".

**Comment by mrimann** [comment] 2020-06-08 10:37
A short update after two months: We're still running those checks with this plugin - and it got rather quiet in the last weeks. We've just seen certain single hickups that went away before a human could have a closer look.

So it seems to be kind of a dependency or race condition, maybe a remote server answering a bit too slow under load or something similar.

**Comment by matteocorti** [comment] 2020-06-08 11:36
OK, I'll close the issue for the moment as long as we don't have more information

**Comment by prupert** [comment] 2021-09-13 09:05
I would like to re-open this issue as this OCSP error can cause unwanted CRITICAL state for certificate checks. 

As can be determined from the debug output. **The root cause is a malformed response from an external OCSP server.** 

```
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer "/tmp/check_ssl_certWVvim9" -cert "/tmp/check_ssl_certfgIcrY" -url "http://ocsp.sectigo.com" "" 2>&1
OCSP Error: Responder Error: internalerror (2)
```

See [rfc2560](https://datatracker.ietf.org/doc/html/rfc2560#section-2.3):

>    A server produces the "malformedRequest" response if the request
>    received does not conform to the OCSP syntax.
> 
>    The response "internalError" indicates that the OCSP responder
>    reached an inconsistent internal state. The query should be retried,
>    potentially with another responder.

As a solution to undesired check state I would like to suggest the option in the `check_ssl_cert` script to configure which status code to consider for "OCSP Error: Responder Error: internalerror (2)". Also understand that while an external OCSP responder is misbehaving, all checks that `check_ssl_cert` is doing could still proceed. There is no need to exit the script or consider the certificate invalid solely because an external server is not responding correctly.

**Comment by matteocorti** [comment] 2021-09-13 09:59
I'll take a look

**Comment by matteocorti** [comment] 2021-09-14 12:18
Do you have a server which I could use to test and debug?

**Comment by prupert** [comment] 2021-09-14 12:31
I guess you would want to parse the exit code or stderr output of the `openssl ocsp` command, which is:

`2` i guess? and `OCSP Error: Responder Error: internalerror (2)`

I currently have no certificate checks failing. This is only happening incidentally when there is an issue with an external OCSP responder.

**Comment by matteocorti** [comment] 2021-09-15 10:20
I added an option (```--ignore-ocsp-errors```) to continue of the OSCP server given the internal error. In this way a user can choose if he wants the absolute certainty that the cert is valid or if the OCSP check can be skipped in case of errors

**Comment by prupert** [comment] 2021-09-15 12:33
I noticed that in a regex match on output was added using `grep -F -q -i "internal error"`, I think this should be `"internalerror" in stead, based on the debug output from earlier:

```
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer "/tmp/check_ssl_certWVvim9" -cert "/tmp/check_ssl_certfgIcrY" -url "http://ocsp.sectigo.com" "" 2>&1
OCSP Error: Responder Error: internalerror (2)
```

**Comment by matteocorti** [comment] 2021-09-15 12:36
Sorry! I'll fix it as soon as possible

**Comment by matteocorti** [comment] 2021-09-15 14:27
I just released a quick fix

**Closed** 2021-09-15 14:27 UTC
Labels: bug, enhancement
