### ISSUE TITLE
Check against SMTP server results in extraneous output about MIME types

### ISSUE THREAD

**Issue by frnkblk** [matteocorti/check_ssl_cert#13] opened 2016-05-14 21:24 UTC
```
 ./check_ssl_cert -d -r /etc/ssl/certs -H smtp.premieronline.net -w 30 -c 15 -n *.premieronline.net -p 25 -P smtp  --ignore-sig-alg --altnames
[DBG] ROOT_CA = -CApath /etc/ssl/certs
[DBG] executing with timeout (15s): echo 'Q' | /usr/bin/openssl s_client   -starttls smtp -connect smtp.premieronline.net:25 -servername *.premieronline.net -verify 6 -CApath /etc/ssl/certs  2> /tmp/check_ssl_certa7ZyGL 1> /tmp/check_ssl_certjW0THs
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -starttls smtp -connect smtp.premieronline.net:25 -servername *.premieronline.net -verify 6 -CApath /etc/ssl/certs  2> /tmp/check_ssl_certa7ZyGL 1> /tmp/check_ssl_certjW0THs"
[DBG] check CN: *.premieronline.net
_Warning: unknown mime-type for "\n*.premieronline.net\n" -- using "application/octet-stream"
Error: no such file "\n*.premieronline.net\n"
Warning: unknown mime-type for "\npremieronline.net\n" -- using "application/octet-stream"
Error: no such file "\npremieronline.net\n"_
[DBG] CN check finished
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certjW0THs -noout -checkend 1296000
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certjW0THs -noout -checkend 2592000
SSL_CERT OK - X.509 certificate for '*.premieronline.net' from 'COMODO SSL CA' valid until Jan  7 23:59:59 2018 GMT (expires in 603 days)|days=603;30;15;;
```

**Comment by frnkblk** [comment] 2016-05-14 22:01
Here's another one:

root@nagios:/etc/cron.weekly# /usr/lib/nagios/plugins/check_ssl_cert -r /etc/ssl/certs --ignore-sig-alg --altnames -H mail.ex1.secureserver.net -w 30 -c 15 -n mail.ex1.secureserver.net -p 443
Warning: unknown mime-type for "\nmail.ex1.secureserver.net\n" -- using "application/octet-stream"
Error: no such file "\nmail.ex1.secureserver.net\n"
Warning: unknown mime-type for "\nwww.mail.ex1.secureserver.net\n" -- using "application/octet-stream"
Error: no such file "\nwww.mail.ex1.secureserver.net\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS002\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS002\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS013.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS013.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS003.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS003.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS002.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS002.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS004.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS004.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS007.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS007.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS006\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS006\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS010.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS010.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS003\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS003\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS008.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS008.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS005\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS005\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS010\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS010\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS005.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS005.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS006.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS006.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS008\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS008\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS001.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS001.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS009\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS009\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS007\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS007\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS011.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS011.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS012.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS012.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS011\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS011\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS009.EX1.SECURESERVER.NET\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS009.EX1.SECURESERVER.NET\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS001\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS001\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS012\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS012\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS013\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS013\n"
Warning: unknown mime-type for "\nP3PW5EX1CAS004\n" -- using "application/octet-stream"
Error: no such file "\nP3PW5EX1CAS004\n"
SSL_CERT OK - X.509 certificate for 'mail.ex1.secureserver.net' from 'Starfield Secure Certification Authority' valid until Aug 16 01:56:40 2018 GMT (expires in 823 days)|days=823;30;15;;
root@nagios:/etc/cron.weekly#

**Comment by matteocorti** [comment] 2016-05-15 13:14
I cannot reproduce it: which OS are you using?

```
./check_ssl_cert -H smtp.premieronline.net -w 30 -c 15 -n .premieronline.net -p 25 -P smtp --ignore-sig-alg --altnames -d
[DBG] ROOT_CA = 
[DBG] executing with timeout (15s): echo 'Q' | /opt/local/bin/openssl s_client   -starttls smtp -connect smtp.premieronline.net:25 -servername .premieronline.net -verify 6   2> /var/folders/pd/0hyh93tj0r13f0z06l8yks280000gn/T/check_ssl_certXXXXXX.y4xCpTAS 1> /var/folders/pd/0hyh93tj0r13f0z06l8yks280000gn/T/check_ssl_certXXXXXX.Ia8ZNhdO
SSL_CERT CRITICAL: No certificate returned (verify depth is 6; didn't found starttls in server response, try anyway...; write:
```

**Comment by frnkblk** [comment] 2016-05-15 21:17
I'm running Debian 6.0.10.
Your test may require connecting to port 587.

**Comment by matteocorti** [comment] 2016-05-16 08:26
But none of your examples is about 587. Could you please give an example?

**Comment by frnkblk** [comment] 2016-05-16 14:05
Here's with 587

root@nagios:/usr/lib/nagios/plugins# ./check_ssl_cert -d -r /etc/ssl/certs -H smtp.premieronline.net -w 30 -c 15 -n .premieronline.net -p 587 -P smtp --ignore-sig-alg --altnames
[DBG] ROOT_CA = -CApath /etc/ssl/certs
[DBG] executing with timeout (15s): echo 'Q' | /usr/bin/openssl s_client   -starttls smtp -connect smtp.premieronline.net:587 -servername .premieronline.net -verify 6 -CApath /etc/ssl/certs  2> /tmp/check_ssl_certuseYwO 1> /tmp/check_ssl_certT8VNTW
[DBG]   /usr/bin/timeout 15 /bin/sh -c "echo 'Q' | /usr/bin/openssl s_client   -starttls smtp -connect smtp.premieronline.net:587 -servername .premieronline.net -verify 6 -CApath /etc/ssl/certs  2> /tmp/check_ssl_certuseYwO 1> /tmp/check_ssl_certT8VNTW"
[DBG] check CN: *.premieronline.net
[DBG] the common name .premieronline.net matches ^[A-Za-z0-9-]*[.]premieronline[.]net$
Warning: unknown mime-type for "\n*.premieronline.net\n" -- using "application/octet-stream"
Error: no such file "\n*.premieronline.net\n"
Warning: unknown mime-type for "\npremieronline.net\n" -- using "application/octet-stream"
Error: no such file "\npremieronline.net\n"
[DBG] CN check finished
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certT8VNTW -noout -checkend 1296000
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_certT8VNTW -noout -checkend 2592000
SSL_CERT OK - X.509 certificate for '.premieronline.net' from 'COMODO SSL CA' valid until Jan  7 23:59:59 2018 GMT (expires in 601 days)|days=601;30;15;;
root@nagios:/usr/lib/nagios/plugins#

**Comment by matteocorti** [comment] 2016-05-17 07:28
Ok, it's pretty strange. I still cannot reproduce it on various Linux and OS X machines.

It seems that the problem ist in the alternate names check

```
        # check alterante names
        if [ -n "${ALTNAMES}" ] ; then
            for alt_name in $( $OPENSSL x509 -in "${CERT}" -text | \
                grep --after-context=1 '509v3 Subject Alternative Name:' | \
                tail -n 1 | sed -e "s/DNS://g" | sed -e "s/,//g" ) ; do
                case $COMMON_NAME in
                    $alt_name) ok='true' ;;
                esac
            done
        fi
```

I will try to take a look

**Comment by matteocorti** [comment] 2016-05-17 10:12
I just committed a new version with more debugging output. Can you please try it out?

**Comment by frnkblk** [comment] 2016-05-17 13:20
This works well now, thanks!

**Comment by matteocorti** [comment] 2016-05-17 14:08
Seems to work with the new version

**Closed by matteocorti** 2016-05-17 14:08 UTC
Labels: bug
