### ISSUE TITLE
Handle OCSP timeouts gracefully

### ISSUE THREAD

**Issue by wiebeytec** [matteocorti/check_ssl_cert#83] opened 2018-06-01 08:12 UTC
Earlier this week, the Let's Encrypt OCSP servers went down. This caused all our checks to say 'service check timed out'. We used version 1.54.0 at the time, but looking at the diff, OCSP handling hasn't changed.

Not sure what the best way to deal with outage is. Perhaps `--ignore-ocsp-timeout`? Because I do want to see OCSP errors, but Nagios doesn't have to trip for dozens/hundreds of checks for a benign temporary error that is outside of my control.

**Comment by matteocorti** [comment] 2018-06-25 14:11
Added in 1.69.0

**Comment by matteocorti** [comment] 2018-06-25 14:12
Sorry wrong issue: reopening

**Comment by mtdeguzis** [comment] 2020-03-10 13:33
I am hitting this today too.

```
$ ./check_ssl_cert '--ignore-sig-alg' '-H' '<IP>' '-c' '14' '-p' '<PORT>' '-w' '30'

# Hangs:
++ /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certTMd2Wq -cert /tmp/check_ssl_certW42FLd -url http://ocsp.entrust.net -header HOST ocsp.entrust.net
```

http://ocsp.entrust.net/ resolves, but the page is blank. There doesn't seem to be a status page for OCSP.

There should be a fallback method/cache/URL or sorts to handle these cases.

**Comment by matteocorti** [comment] 2020-03-10 13:35
Hi

I would like to reproduce the problem to test. Could you please post the parameter you are using and the output with `-d`?

Matteoi

**Comment by mtdeguzis** [comment] 2020-03-10 13:44
```
$ curl -LJO "https://github.com/matteocorti/check_ssl_cert/releases/download/v1.111.0/check_ssl_cert-1.111.0.tar.gz"
$ tar --strip-components=1 -xf check_ssl_cert-*.tar.gz check_ssl_cert-*/check_ssl_cert
$ ./check_ssl_cert '--ignore-sig-alg' '-H' '<HOST>' '-c' '14' '-p' '8444' '-w' '30' -d 2>&1 | tee /tmp/check_ssl_debug.txt
```
Debug:
```
[DBG] -c specified: 14
[DBG] ROOT_CA = 
[DBG] cURL binary needed. SSL Labs = , OCSP = 1
[DBG] cURL binary not specified
[DBG] cURL available: /usr/bin/curl
[DBG] nmap binary not needed. No disallowed protocols
expect available (/usr/bin/expect)
timeout available (/usr/bin/timeout)
[DBG] perl available: /usr/bin/perl
[DBG] date available: /usr/bin/date
found GNU date with timestamp support: enabling date computations
[DBG] check_ssl_cert version: 1.111.0
[DBG] OpenSSL binary: /usr/bin/openssl
[DBG] OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
[DBG] OpenSSL configuration directory: /etc/pki/tls
[DBG] 133 root certificates installed by default
[DBG] System info: Linux host.domain.com 3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[DBG] Date computation: GNU
[DBG] '/usr/bin/openssl s_client' supports '-servername': using -servername <TARGET_IP>
[DBG] '/usr/bin/openssl s_client' supports '-name': using host.domain.com
[DBG] '/usr/bin/openssl s_client' supports '-xmpphost': using -xmpphost <TARGET_IP>
[DBG] temporary file /tmp/check_ssl_cert8I8fC8 created
[DBG] temporary file /tmp/check_ssl_certjWXC6x created
[DBG] temporary file /tmp/check_ssl_certr0AlTj created
[DBG] temporary file /tmp/check_ssl_certCyeZue created
downloading certificate to /tmp
[DBG] <TARGET_IP> is an IPv4 address
[DBG] executing with timeout (15s): printf 'HEAD / HTTP/1.1\nHost: <TARGET_IP>\nUser-Agent: check_ssl_cert/1.111.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect <TARGET_IP>:<PORT> -servername <TARGET_IP> -showcerts -verify 6       2> /tmp/check_ssl_certjWXC6x 1> /tmp/check_ssl_cert8I8fC8
[DBG]   /usr/bin/timeout 15 /bin/sh -c "printf 'HEAD / HTTP/1.1\nHost: <TARGET_IP>\nUser-Agent: check_ssl_cert/1.111.0\nConnection: close\n\n' | /usr/bin/openssl s_client    -crlf -ign_eof  -connect <TARGET_IP>:<PORT> -servername <TARGET_IP> -showcerts -verify 6       2> /tmp/check_ssl_certjWXC6x 1> /tmp/check_ssl_cert8I8fC8"
[DBG] Return value of the command = 0
[DBG] storing a copy of the retrieved certificate in /tmp/<TARGET_IP>-<PORT>.crt
[DBG] storing a copy of the OpenSSL errors in /tmp/<TARGET_IP>-<PORT>.error
parsing the x509 certificate file
[DBG] ISSUERS = 
[DBG]           Entrust Certification Authority - L1K
[DBG]           Entrust Root Certification Authority - G2
[DBG]           Entrust Root Certification Authority - G2
[DBG] subject= C = US, ST = <SOMEWHERE>, L = Nowhereville, O = <MY_ORG> System Services, CN = <HOST>.<MY_ORG>.<COM>
[DBG] CN         = <HOST>.<MY_ORG>.<COM>
[DBG] CA         = Entrust Certification Authority - L1K
[DBG] CA         = Entrust Root Certification Authority - G2
[DBG] CA         = Entrust Root Certification Authority - G2
[DBG] SERIAL     = 3B84411928AB20650000000050F54852
[DBG] FINGERPRINT= B8:D4:FA:CE:D5:38:BF:D6:2F:E2:C3:2D:02:6E:16:92:56:27:AD:0C
[DBG] OCSP_URI   = http://ocsp.entrust.net
[DBG] ISSUER_URI = http://aia.entrust.net/l1k-chain256.cer
[DBG]     Signature Algorithm: sha256WithRSAEncryption
[DBG] Date computations: GNU
[DBG] Computing number of hours until 'Aug  2 18:53:25 2021 GMT'
[DBG] Hours until Aug  2 18:53:25 2021 GMT: 12245
The certificate will expire in 510 day(s)
[DBG] subjectAlternativeName = <HOST>.<MY_ORG>.<COM> www.<HOST>.<MY_ORG>.<COM>
[DBG] Checking expiration date
[DBG] critical = 14
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert8I8fC8 -noout -checkend 1209600
[DBG] executing: /usr/bin/openssl x509 -in /tmp/check_ssl_cert8I8fC8 -noout -checkend 2592000
[DBG] Checking revokation via OCSP
[DBG] OCSP: fetching issuer certificate http://aia.entrust.net/l1k-chain256.cer to /tmp/check_ssl_certr0AlTj
[DBG] executing with timeout (15s): /usr/bin/curl --silent --location http://aia.entrust.net/l1k-chain256.cer > /tmp/check_ssl_certr0AlTj
[DBG]   /usr/bin/timeout 15 /bin/sh -c "/usr/bin/curl --silent --location http://aia.entrust.net/l1k-chain256.cer > /tmp/check_ssl_certr0AlTj"
[DBG] OCSP: issuer certificate type:  data
[DBG] OCSP: converting issuer certificate from DER to PEM
[DBG] OCSP: storing a copy of the retrieved issuer certificate to /tmp/l1k-chain256.cer
[DBG] OCSP: host = ocsp.entrust.net
[DBG] /usr/bin/openssl ocsp supports the -header option
[DBG] /usr/bin/openssl ocsp -header requires 'key value'
[DBG] executing /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certr0AlTj -cert /tmp/check_ssl_cert8I8fC8  -url http://ocsp.entrust.net  -header HOST ocsp.entrust.net
```

**Comment by matteocorti** [comment] 2020-03-10 14:27
Without the host I cannot reproduce since I should find another one with the same behaviour. I don't understand all this secrecy. It's just an host name.

Anyway: I develop the tool as hobby and I release it for free. If you want help, and I have to invest my time analysing the problem I need to be able to work on it.

Without an host that I  could use to reproduce the problem I will not be able to work on it.

**Comment by mtdeguzis** [comment] 2020-03-10 14:37
It's an internal host on Entrust, so I cannot give you that, but you could validate against many other hosts. I don't know how to just dig up a host that uses entrust. The original post asked for a timeout function. I'll just implement that from your args I suppose. I very much appreciate your efforts, but I hope you understand that company information on an internal cert cannot be given.

```
$ /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certDRzkLE -cert /tmp/check_ssl_cert0WdfLs  -url http://ocsp.entrust.net  -header HOST ocsp.entrust.net -timeout 15
Timeout on request
Error querying OCSP responder
```
There doesn't seem to be a way to health check http://ocsp.entrust.net. I would have thought that there would be some kind of sane timeout by default on http://ocsp.entrust.net since it is heavily leaned upon for functionality of this tool. I tried adding `--timeout 15` to this check, but it did not produce the same message or time out as you see above with openssl.

```
$ bash - -x ./check_ssl_cert '--ignore-sig-alg' '-H' '<HOST>' '-c' '14' '-p' '8444' '-w' '30' --timeout 15

++ /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certh4P2YI -cert /tmp/check_ssl_cert1FEuxh -url http://ocsp.entrust.net -header HOST ocsp.entrust.net
```

Am I using the wrong args? I'll try to submit a PR if this timeout functionality is not for the openssl command (seen above).

**Comment by matteocorti** [comment] 2020-03-10 14:40
I understand but I will not begin implementing something I cannot test. It will take too much time and will most likely just produce problems.

**Comment by mtdeguzis** [comment] 2020-03-10 14:49
I ran your own unit tests adding `bash -x` before ${SCRIPT} to show the check_ssl actions. This also hangs. I am more than willing to work on resolving this via the unit_test.sh script. We should be able to add or have a sane default for the below command
```
$ bash unit_tests.sh

+ KEYVALUE=
+ /usr/bin/openssl ocsp -help
+ grep header
+ grep -q key=value
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
++ /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certTmAQUz -cert /tmp/check_ssl_certLVeqHM -url http://ocsp.quovadisglobal.com -header HOST ocsp.quovadisglobal.com
```

Again, test with openssl:
```
$ /usr/bin/openssl ocsp -no_nonce -issuer /tmp/check_ssl_certDRzkLE -cert /tmp/check_ssl_cert0WdfLs  -url http://ocsp.entrust.net  -header HOST ocsp.entrust.net -timeout 15
Timeout on request
Error querying OCSP responder
```
 "Error querying OCSP responder" should be reported with some sane timeout.

**Comment by matteocorti** [comment] 2020-03-10 15:06
Again: I cannot test as I don't have the issuer certificate (`/tmp/check_ssl_certDRzkLE`) and the certificate (`/tmp/check_ssl_cert0WdfLs`)

**Comment by mtdeguzis** [comment] 2020-03-10 15:07
@matteocorti , I am running your own unit tests and they do not complete. It is fine that we don't focus on my cert itself, the aim of this issue to to solve/come up with a sane solution/workaround to http://ocsp.entrust.net/ timing out.

**Comment by mtdeguzis** [comment] 2020-03-10 15:12
Reproducible steps:
```
git clone https://github.com/matteocorti/check_ssl_cert
cd check_ssl_cert
git clone https://github.com/kward/shunit2
cd tests
export SHUNIT2=../shunit2/shunit2

# add a bit of verbosity
vim unit_tests.sh 
:%s/${SCRIPT}/bash -x ${SCRIPT}/g

bash -x unit_tests.sh 2>&1 | tee /tmp/unit_test-debug.log
```
[unit_test-debug.log](https://github.com/matteocorti/check_ssl_cert/files/4313165/unit_test-debug.log)

**Comment by matteocorti** [comment] 2020-03-10 15:23
I am testing from different machines (macOS, Linux) from Switzerland, Germany and USA. I am not able to reproduce any problems.

**Comment by mtdeguzis** [comment] 2020-03-10 15:25
It could be that our org is blocking the request, let me disconnect from my work VPN and retest. Even if it's my VPN, would you be open to a PR or adding a timeout for the OCSP check with openssl?

**Comment by mtdeguzis** [comment] 2020-03-10 15:32
Confirmed it is indeed some MITM checking by our org. I'll leave the timeout addition question up to you, PR or not, but it'd be nice to know what* is going wrong if the OCSP cannot be reached, same as openssl showing you the timeout as demonstrated.

**Comment by matteocorti** [comment] 2020-03-10 20:30
Ok. I can then try to reproduce the case by adding a fake entry in `/etc/hosts/` for any OCSP server. I'll try.

**Comment by arekm** [comment] 2020-03-31 07:41
Today I'm also hitting OCSP problems with letsencrypt servers (here openssl ocsp tries to use IPv6 to connect to OCSP servers but there seem to be problems with that).

Anyway connect to such servers takes much longer than nagios wants to wait for check_ssl cert to finish. I think all calls to ocsp servers should have explicit and not so big timeout like

-                            OCSP_RESP="$(${OPENSSL} ocsp -no_nonce -issuer "${ISSUER_CERT}" -cert "${CERT}" -url "${OCSP_URI}" 2>&1 )"
+                            OCSP_RESP="$(${OPENSSL} ocsp -timeout 10 -no_nonce -issuer "${ISSUER_CERT}" -cert "${CERT}" -url "${OCSP_URI}" 2>&1 )"

(+ all other openssl ocsp calls)

or use exec_with_timeout thing

That and what issue creator said (--ignore-ocsp-timeout) would solve the problem.

**Comment by arekm** [comment] 2020-03-31 08:15
Note: Would be nice to append that timeout message to actual "OK" output when --ignore-ocsp-timeout is used like

````
SSL_CERT OK - x509 certificate 'example.com' from 'Let's Encrypt Authority X3' valid until May  1 04:54:37 2020 GMT (expires in 30 days). OCSP: Timeout on connect|days=30;20;10;;
````

which my pull request doesn't .

**Closed** 2020-04-07 14:02 UTC
Labels: enhancement, help wanted
